from gymnasium.envs.registration import register
from .Wind_Farm_Env import WindFarmEnv
from .AgentEval import AgentEval
from .Agents import PyWakeAgent
from .FarmEval import FarmEval
from .WindEnvMulti import WindFarmEnvMulti
from .AgentEval import eval_single_fast as AgentEvalFast

register(
    id="WindGym/WindFarmEnv-v0",
    entry_point="WindGym.envs:WindFarmEnv",
)

try:
    # generated by setuptools-scm because of [tool.setuptools_scm].version_file
    from .version import version as __version__
except Exception:
    # ultimate fallback for odd environments
    try:
        from importlib.metadata import version, PackageNotFoundError

        __version__ = version("WindGym")
    except Exception:
        __version__ = "0.0.0"
